### ISSUE TITLE
Old behaviour

### ISSUE THREAD

**Issue by christophlehmann** [einpraegsam/email2powermail#2]
Hi Alex,

thanks for porting the extension to be 7.6 ready! The old behaviour was to change *every* mail link.

I wrote an alternative EmailLinkFactory to restore that behaviour. It also keeps the original link attributes which would be nice to see in yours.

https://gist.github.com/christophlehmann/8a1fe9c59396bb96c595a8ac34553a23

Are you interested in an integration?

PS: forget my PR from yesterday ;-)

Viele Grüße
Christoph

**Comment by einpraegsam** [comment]
Hi Christoph,

I never installed this extension on any production system. It was just a timefiller.
If you think it's a good idea to have a simple mode without database connection for specified emails, you can create a pull request.

But please include this:
- A switch (checkbox in ext_conf_template.txt) to enable the simple mode
- A new function ConfigurationUtility::isInSimpleMode()
- Switch in \In2code\Email2powermail\Domain\Service\Replace to use EmailLinkFactory or the SimpleEmailLinkFactory
- In addition we should hide the table tx_email2powermail_domain_model_email from backend list view if simple mode is turned on. A TSConfig in ext_tables.php should do the trick with `mod.web_list.table.tx_email2powermail_domain_model_email.hideTable = 1`

What do you think?

Alex

**Comment by christophlehmann** [comment]
Sounds good.

In my class i use the db table for caching reasons email <=> uid, so i would not hide the table, okay?

I will make a PR soon.

**Comment by einpraegsam** [comment]
Let's think for general cases not just for your use-case.
You could enable the tables if your template extension overwrites the TSConfig.
Am I wrong or do most users don't need the tables if they will use the simple mode?

**Comment by christophlehmann** [comment]
Hi Alex,

we use the extension for data privacy reasons not only for hiding addresses from spider. Hiding addresses could be easier done with https://docs.typo3.org/typo3cms/TyposcriptReference/Setup/Config/Index.html#spamprotectemailaddresses where i hope that it's safe ;-) I'm sure you know the setting.

At first i thought about not using the database table in combination with an bi-directional encryption for encoding/decoding the links, in it's simplest form with base64. But this seams not really safe, so my next idea is to use the table for address<=>uid mapping where the name field doesn't matter. Users need to be teached not to write the email address down and link it with a mail link.

Yes, you are right - in simple mode we can hide the table in TSConfig

So, is it okay for you to use the database table for mapping in simple mode?

**Comment by einpraegsam** [comment]
Merged :)
