### ISSUE TITLE
Email records disappear in BE list view when basic.enableSimpleMode is set

### ISSUE THREAD

**Issue by Pavitro** [einpraegsam/email2powermail#9]
When basic.enableSimpleMode is off, they appear again.
TYPO3 7.6.23 PHP 7.0.20-1~dotdeb+8.1

**Comment by einpraegsam** [comment]
What do you mean with "they appear again"? Pls describe the problem a bit more. Sometimes screenshots help to understand the issue.
In addtion pls tell me which powermail and which email2powermail version do you use.

**Comment by Pavitro** [comment]
When I create records in Listview, the records are only visible when simple mode is **off**.
simplemode checked > **no** records visible in listview
simplemode **un**checked > records visible in listview
I'm using powermail 3.22.1 and email2powermail 1.1.1

OK, there seems to be a brand new version now, maybe I should try that one.

**Comment by einpraegsam** [comment]
Yes of course, simple mode does not work with records of type tx_email2powermail_domain_model_email. Technically the line page TSConfig is added when you activate simplemode: mod.web_list.table.tx_email2powermail_domain_model_email.hideTable = 1

Or in other words: If you need this records, you don't have to activate the simple mode.
